### PR TITLE
Issue #335 - Update lib.rs to lastest librustzcash master

### LINKED ISSUE #335: Update lib.rs to lastest librustzcash master

### LINKED ISSUE #373: Demo App shows ZEC balances in scientific notation
### Describe the issue
Demo App shows ZEC balances in scientific notation

### Can you reliably reproduce the issue?
yes. just check the balance

### Expected behaviour
Show numbers for the rest of the world 😅

- App Version: 
- iOS Version:
- Device: (if applies)

### LINKED ISSUE #374: XCTest don't load Resources from the module's bundle
### Describe the issue
When running tests from Xcode the test databases can't be loaded from the module's Bundle.

#### If so, please list the steps to reproduce below:
run the `testWalletInitialization` test.

### Expected behavior
Test runs.

Test fails with forced unwrap exception on nil 

### Actual behaviour + errors

When inspected on lldb on a breakpoint `po Bundle.module` returns (not loaded) 

see: https://stackoverflow.com/questions/47177036/use-resources-in-unit-tests-with-swift-package-manager

### LINKED ISSUE #375: User can't go twice in a row to SendFundsViewController
### Describe the issue
When the user goes to the Send Funds section of the app and then back to the main screen, synchronizer fails to start when the user attempts to go back to the Send Funds screen.

### Expected behaviour
User should be able to actually go back and forth to a given section of the app w/o problems

### LINKED ISSUE #380: One of the initAccountsTable() is dead code (except for tests)
It doesn't look like this function is used anywhere except for tests:

https://github.com/zcash/ZcashLightClientKit/blob/80e6ec200bcc2d52e2965aefcdd19dd9c266db10/Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift#L97-L112

Maybe we can change the tests to use the new one and then delete this? (The corresponding thing in `zcash-light-client-ffi` might need to be deleted too once all SDKs are upgraded to no longer use it.)

### PR DESCRIPTION
**Pull request by pacu**
closes #335 

bonuses:
closes #375
closes #374
closes #373 
closes #380

This is an ongoing work to update the FFI component to the latest librustzcash c
ode present in master branch in the verge of the release of zcashd 4.7.0
this adopts the Account Keys approach and deprecates the use of WIF enconded transparent private keys

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [ ] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [ ] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [x] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [x] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [x] Automated tests: Did you review the automated tests?
- [x] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

### CODE REVIEW

**Comment by pacu** [comment]
offline tests state 
image

File: Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift [hunk 1]
```diff
@@ -94,28 +96,11 @@ class ZcashRustBackend: ZcashRustBackendWelding {
...
-
-        return extsks
-    }
-    
     static func initAccountsTable(dbData: URL, uvks: [UnifiedViewingKey], networkType: NetworkType) throws -> Bool {
         let dbData = dbData.osStr()
         
         var ffiUvks: [FFIUnifiedViewingKey] = []
-        for uvk in uvks {
+        for (accountIndex, uvk) in uvks.enumerated() {
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift:103]: This seems a little fragile, but probably ok for now considering there's ordinarily only one account.

File: Sources/ZcashLightClientKit/Tool/DerivationTool.swift [hunk 2]
```diff
@@ -72,18 +72,26 @@ public protocol KeyDeriving {
...
+
     /**
     Derives a SecretKey to spend transparent funds from a transparent secret key wif encoded
     */
     func deriveTransparentPrivateKey(seed: [UInt8], account: Int, index: Int) throws -> String
-    
+
     /**
-    Derives a transparent address from the given transparent Secret Key
+    Derives a transparent address from the given transparen t Secret Key
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Tool/DerivationTool.swift:82]:
```suggestion
    Derives a transparent address from the given transparent Secret Key
```

File: Sources/ZcashLightClientKit/Tool/DerivationTool.swift [hunk 3]
```diff
@@ -72,18 +72,26 @@ public protocol KeyDeriving {
...
+
+    /// Derives the transparent Address for the given Secp256k1 Public Key
+    /// - Parameter string encoded Secp256k1 public key
+    /// - Returns String encoded transparent address
     func deriveTransparentAddressFromPublicKey(_ pubkey: String) throws -> String
+
+    /// Derives the index 0 transparent Address for the given Account Public Key
+    /// - Parameter accountPubKey string encoded account pubkey, as found on UnifiedViewingKey
+    /// - Returns String encoded transparent address
+    func deriveTransparentAddressFromAccountPublicKey(_ accountPubKey: String) throws -> String
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Tool/DerivationTool.swift:94]: nonblocking: it'd be nice if these strings had wrapper types around them to avoid confusion.

**Review by nuttycom — APPROVED** [review]
utACK
