### PR TITLE
[#677] Add support for wipe into SDK

### LINKED ISSUE #677: [657_download_change] SDK can't sync after all files are deleted (wipe)
I accidentally tapped wipe when trying to rescan the ECC Wallet. when I opened the app again the app failed to resume scanning from scratch

use ECC Wallet branch `change_how_blocks_sync`. 
Sync a wallet.
go to profile > rescan > wipe
relaunch app.

````
2022-12-15 11:31:03.287966-0300 ECC-Wallet-Testnet[19059:161308] [] CompactBlockProcessor[594] - processNewBlocks(ranges:) - DEBUG 🐞 - Syncing with ranges:
downloaded but not scanned: 1410001...2152818
download and scan:          -1...-1
enhance range:              -1...-1
fetchUTXO range:            -1...-1
total progress range:       1410001...2152818
2022-12-15 11:31:03.288046-0300 ECC-Wallet-Testnet[19059:161336] [] CompactBlockProcessor[609] - processNewBlocks(ranges:) - DEBUG 🐞 - Starting scan with downloaded but not scanned blocks with range: 1410001...2152818
````

````
CompactBlockProcessor[594] - processNewBlocks(ranges:) - DEBUG 🐞 - Syncing with ranges:
downloaded but not scanned: 0...1409900
download and scan:          1410000...2152828
enhance range:              1410000...2152828
fetchUTXO range:            1410000...2152828
total progress range:       0...2152828
2022-12-15 11:34:06.925596-0300 ECC-Wallet-Testnet[19059:163094] [] CompactBlockProcessor[609] - processNewBlocks(ranges:) - DEBUG 🐞 - Starting scan with downloaded but not scanned blocks with range: 0...1409900
2022-12-15 11:34:06.933998-0300 ECC-Wallet-Testnet[19059:161309] [] CompactBlockProcessor[614] - processNewBlocks(ranges:) - DEBUG 🐞 - Starting sync with range: 1410000...2152828
2022-12-15 11:34:06.934134-0300 ECC-Wallet-Testnet[19059:161309] [] CompactBlockDownload[44] - downloadAndScanBlocks(at:totalProgressRange:) - DEBUG 🐞 - Sync loop #1 range: 1410000...1410099
2022-12-15 11:34:06.934191-0300 ECC-Wallet-Testnet[19059:163094] [] CompactBlockDownload[104] - downloadAndStoreBlocks(using:at:maxBlockBufferSize:) - DEBUG 🐞 - Downloading blocks in range: 1410000...1410099
`````

### PR DESCRIPTION
**Pull request by Chlup**
Closes #677

- Previously when keychain wanted to do wipe wallet had to do it on it's own. Which isn't good. Now wallet can simply call `synchronizer.wipe()` and it's done.
- This change brings support for wipe. `Synchronizer` has new method `wipe()` which takes care of everything. All the database connections are closed. Databases are removed. `InternalSyncProgress` is reset.

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [x] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [ ] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

### CODE REVIEW

File: Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift [hunk 1]
```diff
@@ -565,6 +566,13 @@ public actor CompactBlockProcessor {
         return rewindBlockHeight
     }
 
+    func wipe() async throws {
+        guard shouldStart else { throw CompactBlockProcessorError.wipeAttemptWhileProcessing }
```
Comment (pacu) [inline Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift:570]: I have a doubt about using `shouldStart` because it's a slightly different scenario. Imagine that you are wiping the SDK because of a recurring error as a troubleshooting step. 

````Swift
    var shouldStart: Bool {
        switch self.state {
        case .stopped, .synced, .error:
            return !maxAttemptsReached
        default:
            return false
        }
    }
````

`shouldStart` would prevent you from doing so. Because you can't start the processor if you've reached the max retry attempts. 

I thing we want to introduce a different logic here tailored to the specific scenarios where a `wipe()` could be called

Comment (Chlup) [reply Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift]: I updated the changelog and changed condition in `CompactBlockProcessor.wipe()`.

**Review by pacu — APPROVED** [review]
