### PR TITLE
Fix inverted sync status flags

### LINKED ISSUE #1154: Logic error in `SyncStatus` enum
### Describe the issue
In `Synchronizer.swift`, there is an enum `SyncStatus` that provides the following 3 convenience properties:

```
public var isSyncing: Bool {
        guard case .syncing = self else { return true }
        return false
}
    
public var isSynced: Bool {
       guard case .upToDate = self else { return true }
       return false
}

public var isPrepared: Bool {
       guard case .unprepared = self else { return false }
       return true
}
```

There are a couple issues with this:
1. The logic is simply wrong. Each of these is inverted.
2. Using guard here is confusing (and probably what led to this logic error). Generally, guard is used to bail early if a precondition is unmet. In this case, we're mapping a case value to a Bool flag. Better to use a simple if check, which is in fact what the analogous `InternalSyncStatus` does. In fact, one could argue the implementation for both should be the same for consistency.

#### If so, please list the steps to reproduce below:
1. Try to check on the sync status by using one of these utility properties.

### Expected behaviour
Tell us what should happen
In my use case, if the SDK is syncing (thus isSyncing should return true), I want to show an indeterminate progress bar. 

### Actual behaviour + errors
Tell us what happens instead including any noticeable error output (any messages
displayed on-screen when e.g. a crash occurred)

The app syncs with no loading indicator, and when the sync finished, the loading indicator shows (because the logic is reversed)

- App Version: 
- iOS Version:
- Device: (if applies)

### PR DESCRIPTION
**Pull request by tw0po1nt**
Closes #1154 

This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [x] Automated tests: Did you add appropriate automated tests for any code changes?
- [x] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [x] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [x] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [x] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [ ] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [ ] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

### CODE REVIEW

File: Sources/ZcashLightClientKit/Synchronizer.swift [hunk 1]
```diff
@@ -336,17 +336,26 @@ public enum SyncStatus: Equatable {
     case error(_ error: Error)
     
     public var isSyncing: Bool {
-        guard case .syncing = self else { return true }
+        if case .syncing = self {
```
Comment (pacu) [inline Sources/ZcashLightClientKit/Synchronizer.swift:339]: Good catch @tw0po1nt. 

This should have broken a few tests. 🥶

Comment (LukasKorba) [reply Sources/ZcashLightClientKit/Synchronizer.swift:339]: None actually, at least in Zcash case. The computed variables are not used anywhere in the Zcash code.
