### PR TITLE
Type safe address api

### LINKED ISSUE #461: Wallet Address Types
Make a Type safe Address type where
- Every Address and Unified Spending/Viewing Key has it's own type
- types can't be used interchangeably by mistake
- hides encoding until it needs to be represented as String for UI purposes.

### LINKED ISSUE #510: Change references of Shielded address to Sapling Address
raised by @nuttycom 
https://github.com/zcash/ZcashLightClientKit/pull/491#discussion_r955479724

### LINKED ISSUE #517: Ensure that Keys can't be accidentally leaked by loggers
Make sure that Users' keys can't be leaked by crash loggers leveraging string interpolation or debug descriptions

### PR DESCRIPTION
**Pull request by pacu**
Closes #461 
Closes #510 
Closes #517 
This code review checklist is intended to serve as a starting point for the author and reviewer, although it may not be appropriate for all types of changes (e.g. fixing a spelling typo in documentation).  For more in-depth discussion of how we think about code review, please see [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md).

# Author

- [x] Self-review: Did you review your own code in GitHub's web interface? Code often looks different when reviewing the diff in a browser, making it easier to spot potential bugs.
- [x] Automated tests: Did you add appropriate automated tests for any code changes?
- [ ] Code coverage: Did you check the code coverage report for the automated tests?  While we are not looking for perfect coverage, the tool can point out potential cases that have been missed.
- [ ] Documentation: Did you update Docs as appropiate? (E.g [README.md](../blob/main/README.md), etc.)
- [x] Run the app: Did you run the app and try the changes? 
- [ ] Did you provide Screenshots of what the App looks like before and after your changes as part of the description of this PR? (only applicable to UI Changes)
- [ ] Rebase and squash: Did you pull in the latest changes from the main branch and squash your commits before assigning a reviewer? Having your code up to date and squashed will make it easier for others to review. Use best judgement when squashing commits, as some changes (such as refactoring) might be easier to review as a separate commit.

# Reviewer

- [x] Checklist review: Did you go through the code with the [Code Review Guidelines](../blob/main/CODE_REVIEW_GUIDELINES.md) checklist?
- [x] Ad hoc review: Did you perform an ad hoc review?  _In addition to a first pass using the code review guidelines, do a second pass using your best judgement and experience which may identify additional questions or comments. Research shows that code review is most effective when done in multiple passes, where reviewers look for different things through each pass._
- [ ] Automated tests: Did you review the automated tests?
- [ ] Manual tests: Did you review the manual tests?_You will find manual testing guidelines under our [manual testing section](../blob/mater/docs/testing/manual_testing)_
- [ ] How is Code Coverage affected by this PR? _We encourage you to compare coverage befor and after your changes and when possible, leave it in a better place. [Learn More...](../blob/master/docs/testing/local_coverage.md)_
- [ ] Documentation: Did you review Docs, [README.md](../blob/master/README.md), [LICENSE.md](../blob/master/LICENSE.md), and [Architecture.md](../blob/master/docs/Architecture.md) as appropriate?
- [ ] Run the app: Did you run the app and try the changes? While the CI server runs the app to look for build failures or crashes, humans running the app are more likely to notice unexpected log messages, UI inconsistencies, or bad output data.

### CODE REVIEW

File: Sources/ZcashLightClientKit/Model/WalletTypes.swift [hunk 1]
```diff
@@ -5,19 +5,159 @@
...
+    public init(encoding: String, network: NetworkType) throws {
+        guard let valid = try? DerivationTool(networkType: network).isValidTransparentAddress(encoding), valid else {
+            throw KeyEncodingError.invalidEncoding
+        }
+
+        self.encoding = encoding
+    }
+}
+
+public struct SaplingAddress: Equatable, StringEncoded {
```
Comment (ccjernigan) [inline Sources/ZcashLightClientKit/Model/WalletTypes.swift:109]: Would it make sense to add a HeaderDoc for SaplingAddress explaining that it is a shielded address, which still works but that SDK developers should prefer UnifiedAddress when possible?

Alternatively, would it make sense to flag this as deprecated?  It wouldn’t mean that it is unsupported, just that UnifiedAddress is the preferred API now?

Comment (pacu) [reply Sources/ZcashLightClientKit/Model/WalletTypes.swift:109]: this is a great catch

**Comment by pacu** [comment]
@str4d  @nuttycom  I updated the code to this branch that builds `librustzcash_0_7` 

https://github.com/zcash-hackworks/zcash-light-client-ffi/tree/bin/librustzcash_0_7

Some of the tests to derive keys fail. 

````
  Assertions: Assertion Failure at DerivationToolTestnetTests.swift:99: XCTAssertEqual failed: ("UnifiedFullViewingKey(encoding: "uviewtest12tkgzhaevmw78us4xj2cx6ehxjgpp5da2qwrjqvytztejqfjdmy3e6nryqggtwrjum5cefuuuky8rscuw5dynmjec2tx3kkupqexw4va879pf874kvp6r8kjeza26gysxllaqwl67hm9u0jjke06zc93asrpw4wmy3g0lr9r5cy9pz49q2g7y7wm2pls5akmzhuvqr7khftk93aa2kpvwp7n3sjtmef28mxg3n2rpctsjlgsrhc29g6r23qc0u4tzd8rz8vqq4j7jxummdts8zx0jatzw4l2tl7r3egxhlw587rtkjx0y6dvw4hf4vjprn0qv3hs0sulmavk84ajeewn7argyerpr4essqvgfd0d24jpz6phxlasnd58qazh9d3yc6ad3hc5atp0pkvlq053zga65gscp0pv2plhqj9y2tcmx43thw5g4v8z3unytkc2dhyttuhmnlh5dyz4rmhgfkc96tp8z8rpfe35whjvky0jagz5n7qx", account: 0)") is not equal to 
("UnifiedFullViewingKey(encoding: "uviewtest16dqd5q7zd3xfxlcm2jm5k95zd92ed3qcm5jr9uq6yl5y2h6vuwfpxlnndckv5hpwsajgvq26xgdcdns8mqclecl0zh4sph45t4ncfnhcsus0k6sashfknsp9ltxrxlf096ljkwmp7psh3z2vmcd3rcc72qaujsl2y23ajexhr7qza29u9k95frs8qqgvy83rgymt7mmw09a02a5ytjpa502tshlsgl2j736jlfuzt27gezlajrs2tw9c99uqxrj5sx942vdr7w6yk2ltz96yq7n96fd9nr48c59dh9znqtwtm0nt9tmt7vzwhdwzt00tgp57mn85hpe6w00upmjv52kct9y", account: 0)")
  File: DerivationToolTestnetTests.swift:9

````


Also it appears that key validation functions don't produce errors when the key is semantically correct but belongs to a different network

````
func testSpendingKeyValidationThrowsWhenWrongNetwork() throws {
        XCTAssertThrowsError(try derivationTool.isValidExtendedSpendingKey("secret-extended-key-main1qw28psv0qqqqpqr2ru0kss5equx6h0xjsuk5299xrsgdqnhe0cknkl8uqff34prwkyuegyhh5d4rdr8025nl7e0hm8r2txx3fuea5mquy3wnsr9tlajsg4wwvw0xcfk8357k4h850rgj72kt4rx3fjdz99zs9f4neda35cq8tn3848yyvlg4w38gx75cyv9jdpve77x9eq6rtl6d9qyh8det4edevlnc70tg5kse670x50764gzhy60dta0yv3wsd4fsuaz686lgszc7nc9vv"))
    }
````

````
  Assertions: Assertion Failure at DerivationToolTestnetTests.swift:113: XCTAssertThrowsError failed: did not throw an error
  File: DerivationToolTestnetTests.swift:113
````

File: Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift [hunk 2]
```diff
@@ -100,6 +103,35 @@ class ZcashRustBackend: ZcashRustBackendWelding {
         return true
     }
 
+    static func isValidExtendedSpendingKey(_ key: String, networkType: NetworkType) throws -> Bool {
+        guard !key.containsCStringNullBytesBeforeStringEnding() else {
+            return false
+        }
+
+        guard zcashlc_is_valid_sapling_extended_spending_key(key, networkType.networkId) else {
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Rust/ZcashRustBackend.swift:111]: If we want to have network-incompatibility identified as a specific failure case that the SDK can recognize, we should change the implementation of this FFI call to return an integer value (0 for success, positive nonzero for "known" errors that the caller should handle, -1 for unrecoverable errors) instead. However, if we wanted to do that we'd have to change how we do parsing in librustzcash, because right now we discard the reason for the parse failure. @str4d do you have an opinion here? https://github.com/zcash/librustzcash/blob/main/zcash_client_backend/src/address.rs#L203 swallows the specific error type; should we return `Result` from these methods instead?

**Review by nuttycom — COMMENTED** [review]
Flushing comments.

File: Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift [hunk 3]
```diff
@@ -59,13 +59,24 @@ public protocol ZcashRustBackendWelding {
...
     
     /**
     - Returns: true when the address is valid and transparent. false in any other case
     - Throws: Error when there's another problem not related to validity of the string in question
     */
     static func isValidExtendedFullViewingKey(_ key: String, networkType: NetworkType) throws -> Bool
-    
+
+    /// - Returns: `true` when the Sapling Extended Spending Key is valid, false in any other case.
+    /// - Throws: Error when the key is semantically valid  but it belongs to another network
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift:75]: I'm not sure how this can be identified as the specific validation error given how we're now doing the parsing, as mentioned before.

File: Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift [hunk 4]
```diff
@@ -327,25 +336,25 @@ public protocol ZcashRustBackendWelding {
...
     /**
-    Derives a set of full viewing keys from a seed
+    Derives a set of Extended Spending Keys from a seed
     - Parameter seed: a string containing the seed
     - Parameter accounts: the number of accounts you want to derive from this seed
     - Returns: an array containing the spending keys
     - Throws: RustBackendError if fatal error occurs
     */
-    static func deriveExtendedSpendingKeys(seed: [UInt8], accounts: Int32, networkType: NetworkType) throws -> [String]?
+    static func deriveExtendedSpendingKeys(seed: [UInt8], accounts: Int32, networkType: NetworkType) throws -> [SaplingExtendedSpendingKey]?
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift:357]:
```suggestion
    static func deriveSaplingExtendedSpendingKeys(seed: [UInt8], accounts: Int32, networkType: NetworkType) throws -> [SaplingExtendedSpendingKey]?
```

File: Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift [hunk 5]
```diff
@@ -327,25 +336,25 @@ public protocol ZcashRustBackendWelding {
...
+
     /**
     Derives a set of full viewing keys from a seed
     - Parameter spendingKey: a string containing the spending key
     - Parameter accounts: the number of accounts you want to derive from this seed
     - Returns: an array containing the derived keys
     - Throws: RustBackendError if fatal error occurs
     */
-    static func deriveExtendedFullViewingKeys(seed: [UInt8], accounts: Int32, networkType: NetworkType) throws -> [String]?
+    static func deriveExtendedFullViewingKeys(seed: [UInt8], accounts: Int32, networkType: NetworkType) throws -> [SaplingExtendedFullViewingKey]?
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift:348]:
```suggestion
    static func deriveSaplingExtendedFullViewingKeys(seed: [UInt8], accounts: Int32, networkType: NetworkType) throws -> [SaplingExtendedFullViewingKey]?
```

File: Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift [hunk 6]
```diff
@@ -327,25 +336,25 @@ public protocol ZcashRustBackendWelding {
     - Returns: the derived key
     - Throws: RustBackendError if fatal error occurs
     */
-    static func deriveExtendedFullViewingKey(_ spendingKey: String, networkType: NetworkType) throws -> String?
-    
+    static func deriveExtendedFullViewingKey(_ spendingKey: SaplingExtendedSpendingKey, networkType: NetworkType) throws -> SaplingExtendedFullViewingKey?
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift:339]:
```suggestion
    static func deriveSaplingExtendedFullViewingKey(_ spendingKey: SaplingExtendedSpendingKey, networkType: NetworkType) throws -> SaplingExtendedFullViewingKey?
```

File: Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift [hunk 7]
```diff
@@ -59,13 +59,24 @@ public protocol ZcashRustBackendWelding {
...
     - Throws: Error when there's another problem not related to validity of the string in question
     */
     static func isValidExtendedFullViewingKey(_ key: String, networkType: NetworkType) throws -> Bool
-    
+
+    /// - Returns: `true` when the Sapling Extended Spending Key is valid, false in any other case.
+    /// - Throws: Error when the key is semantically valid  but it belongs to another network
+    /// - parameter key: String encoded Extendeed Spending Key
+    /// - parameter networkType: `NetworkType` signaling testnet or mainnet
+    static func isValidExtendedSpendingKey(_ key: String, networkType: NetworkType) throws -> Bool
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift:78]:
```suggestion
    static func isValidSaplingExtendedSpendingKey(_ key: String, networkType: NetworkType) throws -> Bool
```

File: Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift [hunk 8]
```diff
@@ -59,13 +59,24 @@ public protocol ZcashRustBackendWelding {
...
+    /// validates whether a string encoded address is a valid Unified Address.
+    /// - Returns: true when the address is valid and transparent. false in any other case
+    /// - Throws: Error when the provided address belongs to another network
+    static func isValidUnifiedAddress(_ address: String, networkType: NetworkType) throws -> Bool
     
     /**
     - Returns: true when the address is valid and transparent. false in any other case
     - Throws: Error when there's another problem not related to validity of the string in question
     */
     static func isValidExtendedFullViewingKey(_ key: String, networkType: NetworkType) throws -> Bool
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift:72]:
```suggestion
    static func isValidSaplingExtendedFullViewingKey(_ key: String, networkType: NetworkType) throws -> Bool
```

File: Sources/ZcashLightClientKit/Synchronizer.swift [hunk 9]
```diff
@@ -95,7 +95,7 @@ public protocol Synchronizer {
     /// Gets the sapling shielded address for the given account.
     /// - Parameter accountIndex: the optional accountId whose address is of interest. By default, the first account is used.
     /// - Returns the address or nil if account index is incorrect
-    func getShieldedAddress(accountIndex: Int) -> SaplingShieldedAddress?
+    func getShieldedAddress(accountIndex: Int) -> SaplingAddress?
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Synchronizer.swift:98]:
```suggestion
    func getSaplingAddress(accountIndex: Int) -> SaplingAddress?
```

File: Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift [hunk 10]
```diff
@@ -683,7 +687,7 @@ public class SDKSynchronizer: Synchronizer {
         initializer.getVerifiedBalance(account: accountIndex)
     }
 
-    public func getShieldedAddress(accountIndex: Int) -> SaplingShieldedAddress? {
+    public func getShieldedAddress(accountIndex: Int) -> SaplingAddress? {
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift:690]:
```suggestion
    public func getSaplingAddress(accountIndex: Int) -> SaplingAddress? {
```

File: Sources/ZcashLightClientKit/Tool/DerivationTool.swift [hunk 11]
```diff
@@ -13,6 +13,10 @@ public protocol KeyValidation {
     func isValidTransparentAddress(_ tAddress: String) throws -> Bool
     
     func isValidShieldedAddress(_ zAddress: String) throws -> Bool
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Tool/DerivationTool.swift:15]:
```suggestion
    func isValidSaplingAddress(_ zAddress: String) throws -> Bool
```

File: Sources/ZcashLightClientKit/Tool/DerivationTool.swift [hunk 12]
```diff
@@ -13,6 +13,10 @@ public protocol KeyValidation {
...
+
+    func isValidExtendedSpendingKey(_ extsk: String) throws -> Bool
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Tool/DerivationTool.swift:17]:
```suggestion
    func isValidSaplingExtendedSpendingKey(_ extsk: String) throws -> Bool
```

File: Sources/ZcashLightClientKit/Tool/DerivationTool.swift [hunk 13]
```diff
@@ -34,7 +38,7 @@ public protocol KeyDeriving {
     
     - Returns: the viewing key that corresponds to the spending key.
     */
-    func deriveViewingKey(spendingKey: String) throws -> String
+    func deriveViewingKey(spendingKey: SaplingExtendedSpendingKey) throws -> SaplingExtendedFullViewingKey
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Tool/DerivationTool.swift:41]:
```suggestion
    func deriveSaplingExtendedFullViewingKey(spendingKey: SaplingExtendedSpendingKey) throws -> SaplingExtendedFullViewingKey
```

File: Sources/ZcashLightClientKit/Tool/DerivationTool.swift [hunk 14]
```diff
@@ -45,7 +49,7 @@ public protocol KeyDeriving {
     
     - Returns: the spending keys that correspond to the seed, formatted as Strings.
     */
-    func deriveSpendingKeys(seed: [UInt8], numberOfAccounts: Int) throws -> [String]
+    func deriveSpendingKeys(seed: [UInt8], numberOfAccounts: Int) throws -> [SaplingExtendedSpendingKey]
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Tool/DerivationTool.swift:52]:
```suggestion
    func deriveSaplingExtendedSpendingKeys(seed: [UInt8], numberOfAccounts: Int) throws -> [SaplingExtendedSpendingKey]
```

Comment (nuttycom) [reply Sources/ZcashLightClientKit/Tool/DerivationTool.swift:52]: I think it's a bit confusing to have these APIs take a number of accounts, whereas the `deriveTransparent*` methods take a single account identifier. My preference would be we change everything to work with single accounts, and that if multiple accounts are required that the caller make multiple calls. Same thing applies to `DeriveUnifiedFullViewingKeys`. Let's fix this now when we're overhauling a lot of stuff, rather than try to make a breaking change later.

File: Sources/ZcashLightClientKit/Tool/DerivationTool.swift [hunk 15]
```diff
@@ -121,32 +115,32 @@ public class DerivationTool: KeyDeriving {
      
     - Returns: the viewing keys that correspond to the seed, formatted as Strings.
     */
-    public func deriveViewingKeys(seed: [UInt8], numberOfAccounts: Int) throws -> [String] {
+    public func deriveUnifiedFullViewingKeys(seed: [UInt8], numberOfAccounts: Int) throws -> [UnifiedFullViewingKey] {
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Tool/DerivationTool.swift:118]: Same comment about the arity of the returned keys.

File: Sources/ZcashLightClientKit/Tool/DerivationTool.swift [hunk 16]
```diff
@@ -166,7 +171,7 @@ public class DerivationTool: KeyDeriving {
     
     - Returns: the spending keys that correspond to the seed, formatted as Strings.
     */
-    public func deriveSpendingKeys(seed: [UInt8], numberOfAccounts: Int) throws -> [String] {
+    public func deriveSpendingKeys(seed: [UInt8], numberOfAccounts: Int) throws -> [SaplingExtendedSpendingKey] {
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Tool/DerivationTool.swift:174]:
```suggestion
    public func deriveSaplingExtendedSpendingKeys(seed: [UInt8], numberOfAccounts: Int) throws -> [SaplingExtendedSpendingKey] {
```
(Modulo return-arity issue)

File: Sources/ZcashLightClientKit/Tool/DerivationTool.swift [hunk 17]
```diff
@@ -189,7 +194,7 @@ public class DerivationTool: KeyDeriving {
      
     - Returns: the address that corresponds to the seed and account index.
     */
-    public func deriveUnifiedAddress(seed: [UInt8], accountIndex: Int) throws -> String {
+    public func deriveUnifiedAddress(seed: [UInt8], accountIndex: Int) throws -> UnifiedAddress {
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Tool/DerivationTool.swift:197]: I think this method needs to change so that the caller is required to provide the diversifier index; with unified addresses, we definitely want to avoid address reuse where possible.

File: Sources/ZcashLightClientKit/Tool/DerivationTool.swift [hunk 18]
```diff
@@ -212,39 +217,28 @@ public class DerivationTool: KeyDeriving {
      
     - Returns: the address that corresponds to the viewing key.
     */
-    public func deriveUnifiedAddress(viewingKey: String) throws -> String {
+    public func deriveUnifiedAddress(from ufvk: UnifiedFullViewingKey) throws -> UnifiedAddress {
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Tool/DerivationTool.swift:220]: Same comment here, we need to pass the diversifier index.

File: Sources/ZcashLightClientKit/Tool/DerivationTool.swift [hunk 19]
```diff
@@ -255,20 +249,24 @@ public class DerivationTool: KeyDeriving {
     */
     public func deriveUnifiedAddressFromUnifiedFullViewingKey(_ ufvk: UnifiedFullViewingKey) throws -> UnifiedAddress {
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Tool/DerivationTool.swift:250]: Same comment here, pass the diversifier index.

File: Sources/ZcashLightClientKit/Tool/DerivationTool.swift [hunk 20]
```diff
@@ -255,20 +249,24 @@ public class DerivationTool: KeyDeriving {
...
-            let encoding = try deriveUnifiedAddress(viewingKey: ufvk.encoding)
-            return ConcreteUnifiedAddress(encoding: encoding)
+            return try deriveUnifiedAddress(from: ufvk)
         } catch {
             throw KeyDerivationErrors.unableToDerive
         }
     }
     
-    public func deriveTransparentAddressFromPublicKey(_ pubkey: String) throws -> String {
+    public func deriveTransparentAddressFromPublicKey(_ pubkey: String) throws -> TransparentAddress {
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Tool/DerivationTool.swift:258]: We need to think carefully about this method, and whether it should continue to exist. It's not clear here whether the pubkey is the account pubkey or the child ("diversified") pubkey. I think my recommendation is that we get rid of transparent and Sapling derivation methods entirely, and make all access to these kinds of legacy addresses route through the unified address derivation system: basically, derive a unified address, then extract the component you want.

File: Sources/ZcashLightClientKit/Tool/DerivationTool.swift [hunk 21]
```diff
@@ -280,7 +278,7 @@ public class DerivationTool: KeyDeriving {
     -  KeyDerivationErrors.derivationError with the underlying error when it fails
     - KeyDerivationErrors.unableToDerive when there's an unknown error
     */
-    public func deriveTransparentAccountPrivateKey(seed: [UInt8], account: Int = 0) throws -> String {
+    public func deriveTransparentAccountPrivateKey(seed: [UInt8], account: Int = 0) throws -> TransparentAccountPrivKey {
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Tool/DerivationTool.swift:281]: Same concern here, we should just get rid of this.

File: Sources/ZcashLightClientKit/Tool/DerivationTool.swift [hunk 22]
```diff
@@ -320,25 +343,76 @@ extension DerivationTool: KeyValidation {
...
-    
-    /**
-    Derives the transparent address from an account private key
-    - Throws:
-        - KeyDerivationErrors.derivationError with the underlying error when it fails
-        - KeyDerivationErrors.unableToDerive when there's an unknown error
-    */
-    public func deriveTransparentAddressFromAccountPrivateKey(_ xprv: String, index: Int) throws -> String {
+
+    public func isValidExtendedSpendingKey(_ extsk: String) throws -> Bool {
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Tool/DerivationTool.swift:347]:
```suggestion
    public func isValidSaplingExtendedSpendingKey(_ extsk: String) throws -> Bool {
```

**Review by nuttycom — APPROVED** [review]
utACK for the current unit of work to achieve an intermediate state that allows internal testing; however, I think that we should essentially change everything over to work in terms of unified keys before we publish a new release.

File: Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift (hunk 3 above)
Comment (pacu) [reply Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift:75]: This is important to catch a this particular user error.

File: Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift [hunk 23]
```diff
@@ -1228,15 +1228,28 @@ extension CompactBlockProcessor {
...
+        guard let address = try? accountRepository.findBy(account: accountIndex)?.address else {
+            return nil
+        }
+
+        return try? UnifiedAddress(encoding: address, network: self.config.network.networkType)
     }
     
-    public func getShieldedAddress(accountIndex: Int) -> SaplingShieldedAddress? {
-        try? accountRepository.findBy(account: accountIndex)?.address
+    public func getShieldedAddress(accountIndex: Int) -> SaplingAddress? {
```
[the remark this answers is not in the document]
Comment (pacu) [reply Sources/ZcashLightClientKit/Block/Processor/CompactBlockProcessor.swift:1275]: tracked here
https://github.com/zcash/ZcashLightClientKit/issues/510

File: Sources/ZcashLightClientKit/Tool/DerivationTool.swift (hunk 17 above)
Comment (pacu) [reply Sources/ZcashLightClientKit/Tool/DerivationTool.swift:197]: tracked here

https://github.com/zcash/ZcashLightClientKit/issues/508

File: Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift (hunk 3 above)
Comment (nuttycom) [reply Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift:75]: Okay. We'll need to change this at least in the FFI layer then, if not in librustzcash itself.

File: Sources/ZcashLightClientKit/Tool/DerivationTool.swift (hunk 14 above)
Comment (pacu) [reply Sources/ZcashLightClientKit/Tool/DerivationTool.swift:52]: tracked here https://github.com/zcash/ZcashLightClientKit/issues/511

File: Sources/ZcashLightClientKit/Tool/DerivationTool.swift (hunk 20 above)
Comment (pacu) [reply Sources/ZcashLightClientKit/Tool/DerivationTool.swift:258]: I removed this since we do have other ways of deriving t-addresses

File: Sources/ZcashLightClientKit/Tool/DerivationTool.swift (hunk 21 above)
Comment (pacu) [reply Sources/ZcashLightClientKit/Tool/DerivationTool.swift:281]: we lack a series of APIs to actually extract these components from the unified keys

Comment (nuttycom) [reply Sources/ZcashLightClientKit/Tool/DerivationTool.swift:260]: Should we just accept the USK at the FFI layer for shielding, and then pass the transparent part of it?

I have a PR for the USK encoding almost ready.

Comment (pacu) [reply Sources/ZcashLightClientKit/Tool/DerivationTool.swift:260]: I think that we can worry about that in a subsequent PR

File: Sources/ZcashLightClientKit/Model/WalletTypes.swift [hunk 24]
```diff
@@ -5,19 +5,159 @@
...
+
+public extension UnifiedAddress {
+
+    /// The tranparent receiver component of this UA if available
+    var transparent: TransparentAddress? {
+        nil
+    }
+
+    /// The Sapling receiver component of this UA if available
+    var sapling: SaplingAddress? {
```
[the remark this answers is not in the document]
Comment (pacu) [reply Sources/ZcashLightClientKit/Model/WalletTypes.swift]: I removed this since it's future coding

File: Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift (hunk 3 above)
Comment (pacu) [reply Sources/ZcashLightClientKit/Rust/ZcashRustBackendWelding.swift:75]: that's ok. I'll track that here https://github.com/zcash/ZcashLightClientKit/issues/509

File: Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift [hunk 25]
```diff
@@ -206,18 +206,19 @@ class SendViewController: UIViewController {
             loggerProxy.warn("WARNING: Form is invalid")
             return
         }
-        
-        guard let address = SampleStorage.shared.privateKey else {
-            loggerProxy.error("NO ADDRESS")
+        // swiftlint:disable:next line_length force_try
+        guard let spendingKey = try! DerivationTool(networkType: kZcashNetwork.networkType).deriveSpendingKeys(seed: DemoAppConfig.seed, numberOfAccounts: 1).first else {
+            loggerProxy.error("NO SPENDING KEY")
```
Comment (LukasKorba) [inline Example/ZcashLightClientSample/ZcashLightClientSample/Send/SendViewController.swift:211]: Too many force unwraps. I know it's the sample code, not a blocking request but I would rather use optional unwrapping.

File: Sources/ZcashLightClientKit/Transaction/WalletTransactionEncoder.swift [hunk 26]
```diff
@@ -107,15 +107,21 @@ class WalletTransactionEncoder: TransactionEncoder {
         }
     }
     
-    func createSpend(spendingKey: String, zatoshi: Int, to address: String, memo: String?, from accountIndex: Int) throws -> Int {
+    func createSpend(
+        spendingKey: SaplingExtendedSpendingKey,
+        zatoshi: Int,
```
Comment (LukasKorba) [inline Sources/ZcashLightClientKit/Transaction/WalletTransactionEncoder.swift:112]: NOTE: Feedback without too much context. Why Int and not a Zatoshi type?

**Review by LukasKorba — APPROVED** [review]
Added only a few non-blocking comments, otherwise LGTM

File: Sources/ZcashLightClientKit/Transaction/TransactionManager.swift [hunk 27]
```diff
@@ -14,17 +14,34 @@ transactions through to completion.
...
-    
-    func submit(pendingTransaction: PendingTransactionEntity, result: @escaping (Result<PendingTransactionEntity, Error>) -> Void)
-    
-    func applyMinedHeight(pendingTransaction: PendingTransactionEntity, minedHeight: BlockHeight) throws -> PendingTransactionEntity
-    
-    func monitorChanges(byId: Int, observer: Any) // check this out. code smell
+    func encodeShieldingTransaction(
+        xprv: TransparentAccountPrivKey,
+        pendingTransaction: PendingTransactionEntity,
+        result: @escaping (Result<PendingTransactionEntity, Error>) -> Void
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Transaction/TransactionManager.swift:27]: Just a style question here: should there be a separate type for like a `SubmittableTransactionEntity` or something like that, so that the data flow is clearer? Right now, from the types it looks like you could just try to call `submit` with a `PendingTransactionEntity` that hasn't yet been encoded; it would be nice for the fact that that would fail to be encoded in the types.

File: Tests/OfflineTests/RecipientTests.swift [hunk 28]
```diff
@@ -0,0 +1,34 @@
...
+//  RecipientTests.swift
+//  OfflineTests
+//
+//  Created by Francisco Gindre on 8/31/22.
+//
+
+import XCTest
+@testable import ZcashLightClientKit
+final class RecipientTests: XCTestCase {
+    let uaString = "u1l9f0l4348negsncgr9pxd9d3qaxagmqv3lnexcplmufpq7muffvfaue6ksevfvd7wrz7xrvn95rc5zjtn7ugkmgh5rnxswmcj30y0pw52pn0zjvy38rn2esfgve64rj5pcmazxgpyuj"
```
Comment (nuttycom) [inline Tests/OfflineTests/RecipientTests.swift:11]: General question: how were these test UA strings derived? It would potentially be a useful thing if these were taken from  the test vectors: https://github.com/zcash-hackworks/zcash-test-vectors/blob/master/test-vectors/json/unified_address.json

**Review by nuttycom — CHANGES_REQUESTED** [review]
This is looking good; there are just a few more things that need to be addressed.

File: Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift [hunk 29]
```diff
@@ -528,10 +529,14 @@ public class SDKSynchronizer: Synchronizer {
                 return
             }
 
-            // TODO: this should be a UA
-            let zAddr = "fasdfasdfa"
+            // FIXME: Define who's the recipient of a shielding transaction #521
+            // https://github.com/zcash/ZcashLightClientKit/issues/521
+            guard let uAddr = self.getUnifiedAddress(accountIndex: accountIndex) else {
```
Comment (nuttycom) [inline Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift:534]: This can be a temporary resolution, so  long as nothing is actually depending upon that address being the address that funds are actually sent to. :grimacing:

File: Sources/ZcashLightClientKit/Model/WalletTypes.swift [hunk 30]
```diff
@@ -5,21 +5,194 @@
...
 /**
  A ZIP 316 Unified Full Viewing Key.
  */
-public protocol UnifiedFullViewingKey {
-    var account: UInt32 { get set }
-    var encoding: String { get set }
+public struct UnifiedFullViewingKey: Equatable, StringEncoded, Undescribable {
+    var encoding: String
+
+    public var account: UInt32
```
[the remark this answers is not in the document]
Comment (str4d) [reply Sources/ZcashLightClientKit/Model/WalletTypes.swift:50]: Currently my belief is that it isn't really part of the public API, because `UnifiedFullViewingKey` is only used in these places:
- As an intermediary between `DerivationTool.deriveUnifiedFullViewingKeysFromSeed` and `ZcashRustBackend.initAccountsTable` (which itself is internal, but is reachable I think publicly via other pathways?).
- To derive UAs in `DerivationTool`, which again is just an intermediary step.
- In tests that check `DerivationTool`.

That's it AFAICT.

If this type is intended to be part of the public API then removing `account` makes sense, and we'd alter `ZcashRustBackend.initAccountsTable` to take a list of `(accountId, UnifiedFullViewingKey)` tuples.

Extending the public API to be a general shielded transaction toolkit isn't really the domain of this SDK, which specifically presents a simplified interface to creating and managing a wallet. I think the correct place for these kinds of APIs would be a sub-library (either one used by this SDK, or next to it).

[the remark this answers is not in the document]
Comment (nuttycom) [reply Sources/ZcashLightClientKit/Model/WalletTypes.swift:50]: Opened https://github.com/zcash/ZcashLightClientKit/issues/522 to track this.

File: Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift (hunk 29 above)
Comment (nuttycom) [reply Sources/ZcashLightClientKit/Synchronizer/SDKSynchronizer.swift:534]: Linking https://github.com/zcash/ZcashLightClientKit/issues/521 for discoverability.

**Review by nuttycom — APPROVED** [review]
utACK; additional required changes are tracked as https://github.com/zcash/ZcashLightClientKit/issues/521 and https://github.com/zcash/ZcashLightClientKit/issues/522
